ecommerce_product:
    resource: "@EcommerceBundle/Resources/config/routing/routingproduct.yml"
    prefix: /product

ecommerce_basket:
    resource: "@EcommerceBundle/Resources/config/routing/routingbasket.yml"
    prefix: /basket

## HOME
ecommerce_homepage: #product list + ???? à déterminer
    path:     /
    defaults: { _controller: EcommerceBundle:Home:index }